package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	models "server/graph/model"
)

// CreateCGuidance is the resolver for the createCGuidance field.
func (r *mutationResolver) CreateCGuidance(ctx context.Context, userID string, input *models.NewCGuidance) (*models.CGuidance, error) {
	panic(fmt.Errorf("not implemented: CreateCGuidance - createCGuidance"))
}

// CGuidance is the resolver for the cGuidance field.
func (r *queryResolver) CGuidance(ctx context.Context, id string) (*models.CGuidance, error) {
	panic(fmt.Errorf("not implemented: CGuidance - cGuidance"))
}

// CGuidances is the resolver for the cGuidances field.
func (r *queryResolver) CGuidances(ctx context.Context, userID string) ([]*models.CGuidance, error) {
	panic(fmt.Errorf("not implemented: CGuidances - cGuidances"))
}
