package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	graphql_models "server/graph/model"
)

// Mentorship is the resolver for the mentorship field.
func (r *queryResolver) Mentorship(ctx context.Context, id string) (*graphql_models.Mentorship, error) {
	panic(fmt.Errorf("not implemented: Mentorship - mentorship"))
}

// Mentorships is the resolver for the mentorships field.
func (r *queryResolver) Mentorships(ctx context.Context, teacherid string) ([]*graphql_models.Mentorship, error) {
	panic(fmt.Errorf("not implemented: Mentorships - mentorships"))
}
