package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	models "server/graph/model"
)

// MentorshipSystem is the resolver for the mentorshipSystem field.
func (r *queryResolver) MentorshipSystem(ctx context.Context, id string) (*models.MentorshipSystem, error) {
	panic(fmt.Errorf("not implemented: MentorshipSystem - mentorshipSystem"))
}

// MentorshipSystems is the resolver for the mentorshipSystems field.
func (r *queryResolver) MentorshipSystems(ctx context.Context, teacherid string) ([]*models.MentorshipSystem, error) {
	panic(fmt.Errorf("not implemented: MentorshipSystems - mentorshipSystems"))
}
