package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	graphql_models "server/graph/model"

	"github.com/99designs/gqlgen/graphql"
)

// CreateMonograph is the resolver for the createMonograph field.
func (r *mutationResolver) CreateMonograph(ctx context.Context, newMonographData graphql_models.MonographData) (*graphql_models.Monograph, error) {
	panic(fmt.Errorf("not implemented: CreateMonograph - createMonograph"))
}

// UpdateMonograph is the resolver for the updateMonograph field.
func (r *mutationResolver) UpdateMonograph(ctx context.Context, id string, monographData graphql_models.MonographData) (*graphql_models.Monograph, error) {
	panic(fmt.Errorf("not implemented: UpdateMonograph - updateMonograph"))
}

// DeleteMonograph is the resolver for the deleteMonograph field.
func (r *mutationResolver) DeleteMonograph(ctx context.Context, id string) (*graphql_models.Monograph, error) {
	panic(fmt.Errorf("not implemented: DeleteMonograph - deleteMonograph"))
}

// UploadMonographs is the resolver for the uploadMonographs field.
func (r *mutationResolver) UploadMonographs(ctx context.Context, file graphql.Upload) ([]*graphql_models.MonographPreview, error) {
	panic(fmt.Errorf("not implemented: UploadMonographs - uploadMonographs"))
}

// CreatedMonographs is the resolver for the createdMonographs field.
func (r *mutationResolver) CreatedMonographs(ctx context.Context, newMonographDatas []*graphql_models.MonographData) ([]*graphql_models.Monograph, error) {
	panic(fmt.Errorf("not implemented: CreatedMonographs - createdMonographs"))
}

// Monograph is the resolver for the monograph field.
func (r *queryResolver) Monograph(ctx context.Context, id string) (*graphql_models.Monograph, error) {
	panic(fmt.Errorf("not implemented: Monograph - monograph"))
}

// Monographs is the resolver for the monographs field.
func (r *queryResolver) Monographs(ctx context.Context, userID string) ([]*graphql_models.Monograph, error) {
	panic(fmt.Errorf("not implemented: Monographs - monographs"))
}

// MonographsByName is the resolver for the monographsByName field.
func (r *queryResolver) MonographsByName(ctx context.Context, name string) ([]*graphql_models.Mentorship, error) {
	panic(fmt.Errorf("not implemented: MonographsByName - monographsByName"))
}
