package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	graphql_models "server/graph/model"

	"github.com/99designs/gqlgen/graphql"
)

// CreatePaper is the resolver for the createPaper field.
func (r *mutationResolver) CreatePaper(ctx context.Context, newPaperData graphql_models.NewPaper) (*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: CreatePaper - createPaper"))
}

// UpdatePaper is the resolver for the updatePaper field.
func (r *mutationResolver) UpdatePaper(ctx context.Context, id string, paperDataL graphql_models.UpdatePaper) (*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: UpdatePaper - updatePaper"))
}

// DeletePaper is the resolver for the deletePaper field.
func (r *mutationResolver) DeletePaper(ctx context.Context, id string) (*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: DeletePaper - deletePaper"))
}

// UploadPaper is the resolver for the uploadPaper field.
func (r *mutationResolver) UploadPaper(ctx context.Context, file graphql.Upload) (*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: UploadPaper - uploadPaper"))
}

// UploadPapers is the resolver for the uploadPapers field.
func (r *mutationResolver) UploadPapers(ctx context.Context, file graphql.Upload) ([]*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: UploadPapers - uploadPapers"))
}

// Paper is the resolver for the paper field.
func (r *queryResolver) Paper(ctx context.Context, id string) (*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: Paper - paper"))
}

// Papers is the resolver for the papers field.
func (r *queryResolver) Papers(ctx context.Context, userID string) ([]*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: Papers - papers"))
}

// PapersByName is the resolver for the papersByName field.
func (r *queryResolver) PapersByName(ctx context.Context, name string) ([]*graphql_models.Paper, error) {
	panic(fmt.Errorf("not implemented: PapersByName - papersByName"))
}
