package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"server/graph"
)

// World is the resolver for the world field.
func (r *mutationResolver) World(ctx context.Context, msg *string) (string, error) {
	panic(fmt.Errorf("not implemented: World - world"))
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context, msg string) (string, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
