// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Class struct {
	ID            string    `json:"id"`
	TeachersIn    []*string `json:"teachersIn"`
	TeachersOut   []*string `json:"teachersOut"`
	ClassName     string    `json:"className"`
	ClassLocation string    `json:"classLocation"`
	ClassType     *string   `json:"classType,omitempty"`
	StartWeek     *int      `json:"startWeek,omitempty"`
	EndWeek       *int      `json:"endWeek,omitempty"`
	StudentNumber *int      `json:"studentNumber,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdateAt      time.Time `json:"updateAt"`
}

type Password struct {
	ID          string    `json:"id"`
	UerID       string    `json:"uerId"`
	URL         *string   `json:"url,omitempty"`
	AppName     *string   `json:"appName,omitempty"`
	Account     string    `json:"account"`
	Password    string    `json:"password"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}

type Query struct {
}

type Term struct {
	ID        string    `json:"id"`
	UserID    string    `json:"userID"`
	TermName  *string   `json:"termName,omitempty"`
	Classes   []*Class  `json:"classes"`
	CreatedAt time.Time `json:"createdAt"`
	UpdateAt  time.Time `json:"updateAt"`
}

type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Password    string    `json:"password"`
	Avatar      string    `json:"avatar"`
	PhoneNumber string    `json:"phoneNumber"`
	WechatToken *string   `json:"wechatToken,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}
