// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_models

import (
	"time"
)

type AcademicTerm struct {
	TermID    string    `json:"termId"`
	TermName  string    `json:"termName"`
	Courses   []*Course `json:"courses"`
	CreatedAt time.Time `json:"createdAt"`
	UpdateAt  time.Time `json:"updateAt"`
}

type AcademicTermPreview struct {
	Term    *string          `json:"Term,omitempty"`
	Courses []*CoursePreview `json:"courses,omitempty"`
}

type AdminSignInInput struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type AuthPayload struct {
	Token string `json:"token"`
}

type AwardSciResearch struct {
	ID         string     `json:"id"`
	AwardName  string     `json:"awardName"`
	AwardDate  *time.Time `json:"awardDate,omitempty"`
	Awardlevel *string    `json:"awardlevel,omitempty"`
	AwardRank  *string    `json:"awardRank,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdateAt   time.Time  `json:"updateAt"`
}

type ChangePassword struct {
	OldPassword *string `json:"oldPassword,omitempty"`
	NewPassword *string `json:"newPassword,omitempty"`
}

type ClassTime struct {
	DayOfWeek int    `json:"dayOfWeek"`
	TimeSlot  string `json:"timeSlot"`
}

type ClassTimePreview struct {
	DayOfWeek *int    `json:"dayOfWeek,omitempty"`
	TimeSlot  *string `json:"timeSlot,omitempty"`
}

type CompGuidance struct {
	ID               string     `json:"id"`
	ProjectName      string     `json:"projectName"`
	StudentNames     []*string  `json:"studentNames"`
	CompetitionScore *string    `json:"competitionScore,omitempty"`
	GuidanceDate     *time.Time `json:"guidanceDate,omitempty"`
	AwardStatus      *string    `json:"awardStatus,omitempty"`
	CreatedAt        time.Time  `json:"createdAt"`
	UpdateAt         time.Time  `json:"updateAt"`
}

type Course struct {
	CourseID       string       `json:"courseId"`
	TeacherNames   string       `json:"teacherNames"`
	CourseName     string       `json:"courseName"`
	CourseLocation *string      `json:"courseLocation,omitempty"`
	CourseType     *string      `json:"courseType,omitempty"`
	CourseWeeks    []*string    `json:"courseWeeks"`
	ClassTimes     []*ClassTime `json:"classTimes"`
	StudentCount   *int         `json:"studentCount,omitempty"`
	Color          *string      `json:"color,omitempty"`
}

type CoursePreview struct {
	TeacherNames   *string      `json:"teacherNames,omitempty"`
	CourseName     *string      `json:"courseName,omitempty"`
	CourseLocation *string      `json:"courseLocation,omitempty"`
	CourseType     *string      `json:"courseType,omitempty"`
	CourseWeeks    []*string    `json:"courseWeeks,omitempty"`
	ClassTimes     []*ClassTime `json:"classTimes,omitempty"`
	StudentCount   *int         `json:"studentCount,omitempty"`
	Color          *string      `json:"color,omitempty"`
}

type EduReform struct {
	ID          string        `json:"id"`
	TeachersIn  []*UserExport `json:"teachersIn"`
	TeachersOut []*string     `json:"teachersOut,omitempty"`
	Number      string        `json:"number"`
	Title       string        `json:"title"`
	StartDate   *time.Time    `json:"startDate,omitempty"`
	Duration    *string       `json:"duration,omitempty"`
	Level       *string       `json:"level,omitempty"`
	Rank        *string       `json:"rank,omitempty"`
	Achievement *string       `json:"achievement,omitempty"`
	Fund        *string       `json:"fund,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdateAt    time.Time     `json:"updateAt"`
}

type Mentorship struct {
	ID           string     `json:"id"`
	ProjectName  string     `json:"projectName"`
	Students     []*string  `json:"students"`
	Grade        *string    `json:"grade,omitempty"`
	GuidanceDate *time.Time `json:"guidanceDate,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdateAt     time.Time  `json:"updateAt"`
}

type Monograph struct {
	ID           string        `json:"id"`
	TeachersIn   []*UserExport `json:"teachersIn"`
	TeachersOut  []*string     `json:"teachersOut,omitempty"`
	Title        *string       `json:"title,omitempty"`
	PublishDate  *time.Time    `json:"publishDate,omitempty"`
	PublishLevel *string       `json:"publishLevel,omitempty"`
	Rank         *string       `json:"rank,omitempty"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdateAt     time.Time     `json:"updateAt"`
}

type Mutation struct {
}

type NewAcademicTerm struct {
	TermName *string      `json:"termName,omitempty"`
	Courses  []*NewCourse `json:"courses"`
}

type NewAwardSciResearch struct {
	AwardName  string     `json:"awardName"`
	AwardDate  *time.Time `json:"awardDate,omitempty"`
	Awardlevel *string    `json:"awardlevel,omitempty"`
	AwardRank  *string    `json:"awardRank,omitempty"`
}

type NewClassTime struct {
	DayOfWeek int    `json:"dayOfWeek"`
	TimeSlot  string `json:"timeSlot"`
}

type NewCompGuidance struct {
	ProjectName      string     `json:"projectName"`
	StudentNames     []*string  `json:"studentNames"`
	CompetitionScore *string    `json:"competitionScore,omitempty"`
	GuidanceDate     *time.Time `json:"guidanceDate,omitempty"`
	AwardStatus      *string    `json:"awardStatus,omitempty"`
}

type NewCourse struct {
	TeacherNames   *string         `json:"teacherNames,omitempty"`
	CourseName     string          `json:"courseName"`
	CourseLocation *string         `json:"courseLocation,omitempty"`
	CourseType     *string         `json:"courseType,omitempty"`
	CourseWeeks    []*string       `json:"courseWeeks"`
	ClassTimes     []*NewClassTime `json:"classTimes"`
	StudentCount   *int            `json:"studentCount,omitempty"`
	Color          *string         `json:"color,omitempty"`
}

type NewEduReform struct {
	TeachersIn  []*string  `json:"teachersIn"`
	TeachersOut []*string  `json:"teachersOut,omitempty"`
	Number      string     `json:"number"`
	Title       string     `json:"title"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	Duration    *string    `json:"duration,omitempty"`
	Level       *string    `json:"level,omitempty"`
	Rank        *string    `json:"rank,omitempty"`
	Achievement *string    `json:"achievement,omitempty"`
	Fund        *string    `json:"fund,omitempty"`
}

type NewSciResearch struct {
	TeachersIn  []*string              `json:"teachersIn"`
	TeachersOut []*string              `json:"teachersOut"`
	Number      *string                `json:"number,omitempty"`
	Title       string                 `json:"title"`
	StartDate   *time.Time             `json:"startDate,omitempty"`
	Duration    *string                `json:"duration,omitempty"`
	Level       *string                `json:"level,omitempty"`
	Rank        *string                `json:"rank,omitempty"`
	Achievement *string                `json:"achievement,omitempty"`
	Fund        *string                `json:"fund,omitempty"`
	IsAward     bool                   `json:"isAward"`
	Awards      []*NewAwardSciResearch `json:"awards"`
}

type NewUser struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type Paper struct {
	ID           string        `json:"id"`
	TeachersIn   []*UserExport `json:"teachersIn"`
	TeachersOut  []*string     `json:"teachersOut"`
	Title        *string       `json:"title,omitempty"`
	PublishDate  *time.Time    `json:"publishDate,omitempty"`
	Rank         *string       `json:"rank,omitempty"`
	JournalName  *string       `json:"journalName,omitempty"`
	JournalLevel *string       `json:"journalLevel,omitempty"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdateAt     time.Time     `json:"updateAt"`
}

type Password struct {
	ID          string    `json:"id"`
	URL         *string   `json:"url,omitempty"`
	AppName     *string   `json:"appName,omitempty"`
	Account     string    `json:"account"`
	Password    string    `json:"password"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}

type Query struct {
}

type ResetPassword struct {
	Email       *string `json:"email,omitempty"`
	Code        *string `json:"code,omitempty"`
	NewPassword *string `json:"newPassword,omitempty"`
}

type SciResearch struct {
	ID          string              `json:"id"`
	TeachersIn  []*UserExport       `json:"teachersIn"`
	TeachersOut []*string           `json:"teachersOut"`
	Number      *string             `json:"number,omitempty"`
	Title       string              `json:"title"`
	StartDate   *time.Time          `json:"startDate,omitempty"`
	Duration    *string             `json:"duration,omitempty"`
	Level       *string             `json:"level,omitempty"`
	Rank        *string             `json:"rank,omitempty"`
	Achievement *string             `json:"achievement,omitempty"`
	Fund        *string             `json:"fund,omitempty"`
	IsAward     bool                `json:"isAward"`
	Awards      []*AwardSciResearch `json:"awards"`
	CreatedAt   time.Time           `json:"createdAt"`
	UpdateAt    time.Time           `json:"updateAt"`
}

type UpdateAcademicTerm struct {
	Name string `json:"name"`
}

type UpdateClassTime struct {
	DayOfWeek *int    `json:"dayOfWeek,omitempty"`
	TimeSlot  *string `json:"timeSlot,omitempty"`
}

type UpdateCourse struct {
	TeacherNames   []*string       `json:"teacherNames,omitempty"`
	CourseName     *string         `json:"courseName,omitempty"`
	CourseLocation *string         `json:"courseLocation,omitempty"`
	CourseType     *string         `json:"courseType,omitempty"`
	CourseWeeks    []*string       `json:"courseWeeks,omitempty"`
	ClassTimes     []*NewClassTime `json:"classTimes,omitempty"`
	StudentCount   *int            `json:"studentCount,omitempty"`
	Color          *string         `json:"color,omitempty"`
}

type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Avatar      string    `json:"avatar"`
	PhoneNumber *string   `json:"phoneNumber,omitempty"`
	WechatToken *string   `json:"wechatToken,omitempty"`
	Activate    bool      `json:"activate"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}

type UserCreate struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserExport struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type UserInfo struct {
	Username    *string `json:"username,omitempty"`
	Avatar      *string `json:"avatar,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}
