// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type AwardScientificResearch struct {
	ID         string     `json:"id"`
	AwardName  string     `json:"awardName"`
	AwardDate  *time.Time `json:"awardDate,omitempty"`
	Awardlevel *string    `json:"awardlevel,omitempty"`
	AwardRank  *string    `json:"awardRank,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdateAt   time.Time  `json:"updateAt"`
}

type CGuidance struct {
	ID           string     `json:"id"`
	ProjectName  string     `json:"projectName"`
	Students     []*string  `json:"students"`
	Grade        *string    `json:"grade,omitempty"`
	GuidanceDate *time.Time `json:"guidanceDate,omitempty"`
	AwardStatus  *string    `json:"awardStatus,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdateAt     time.Time  `json:"updateAt"`
}

type ChangePassword struct {
	OldPassword *string `json:"oldPassword,omitempty"`
	NewPassword *string `json:"newPassword,omitempty"`
}

type Course struct {
	ID            string     `json:"id"`
	Teachers      string     `json:"teachers"`
	Name          string     `json:"name"`
	Location      *string    `json:"location,omitempty"`
	Type          *string    `json:"type,omitempty"`
	Weeks         []*string  `json:"weeks"`
	Schedule      []*Workday `json:"schedule"`
	StudentNumber *int       `json:"studentNumber,omitempty"`
	Background    *string    `json:"background,omitempty"`
}

type CoursePreview struct {
	Teachers      *string    `json:"teachers,omitempty"`
	Name          *string    `json:"name,omitempty"`
	Location      *string    `json:"location,omitempty"`
	Type          *string    `json:"type,omitempty"`
	Weeks         []*string  `json:"weeks,omitempty"`
	Schedule      []*Workday `json:"schedule,omitempty"`
	StudentNumber *int       `json:"studentNumber,omitempty"`
	Background    *string    `json:"background,omitempty"`
}

type EducationReform struct {
	ID          string        `json:"id"`
	TeachersIn  []*UserExport `json:"teachersIn"`
	TeachersOut []*string     `json:"teachersOut,omitempty"`
	Number      string        `json:"number"`
	Title       string        `json:"title"`
	StartDate   *time.Time    `json:"startDate,omitempty"`
	Duration    *string       `json:"duration,omitempty"`
	Level       *string       `json:"level,omitempty"`
	Rank        *string       `json:"rank,omitempty"`
	Achievement *string       `json:"achievement,omitempty"`
	Fund        *string       `json:"fund,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdateAt    time.Time     `json:"updateAt"`
}

type MentorshipSystem struct {
	ID           string     `json:"id"`
	ProjectName  string     `json:"projectName"`
	Students     []*string  `json:"students"`
	Grade        *string    `json:"grade,omitempty"`
	GuidanceDate *time.Time `json:"guidanceDate,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdateAt     time.Time  `json:"updateAt"`
}

type Monograph struct {
	ID           string        `json:"id"`
	TeachersIn   []*UserExport `json:"teachersIn"`
	TeachersOut  []*string     `json:"teachersOut,omitempty"`
	Title        *string       `json:"title,omitempty"`
	PublishDate  *time.Time    `json:"publishDate,omitempty"`
	PublishLevel *string       `json:"publishLevel,omitempty"`
	Rank         *string       `json:"rank,omitempty"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdateAt     time.Time     `json:"updateAt"`
}

type Mutation struct {
}

type NewAwardScientificResearch struct {
	AwardName  string     `json:"awardName"`
	AwardDate  *time.Time `json:"awardDate,omitempty"`
	Awardlevel *string    `json:"awardlevel,omitempty"`
	AwardRank  *string    `json:"awardRank,omitempty"`
}

type NewCGuidance struct {
	ProjectName  string     `json:"projectName"`
	Students     []*string  `json:"students"`
	Grade        *string    `json:"grade,omitempty"`
	GuidanceDate *time.Time `json:"guidanceDate,omitempty"`
	AwardStatus  *string    `json:"awardStatus,omitempty"`
}

type NewCourse struct {
	Teachers      *string       `json:"teachers,omitempty"`
	Name          string        `json:"name"`
	Location      *string       `json:"location,omitempty"`
	Type          *string       `json:"type,omitempty"`
	Weeks         []*string     `json:"weeks"`
	Schedule      []*NewWorkday `json:"schedule"`
	StudentNumber *int          `json:"studentNumber,omitempty"`
	Background    *string       `json:"background,omitempty"`
}

type NewEducationReform struct {
	TeachersIn  []*string  `json:"teachersIn"`
	TeachersOut []*string  `json:"teachersOut,omitempty"`
	Number      string     `json:"number"`
	Title       string     `json:"title"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	Duration    *string    `json:"duration,omitempty"`
	Level       *string    `json:"level,omitempty"`
	Rank        *string    `json:"rank,omitempty"`
	Achievement *string    `json:"achievement,omitempty"`
	Fund        *string    `json:"fund,omitempty"`
}

type NewScientificResearch struct {
	TeachersIn  []*string                     `json:"teachersIn"`
	TeachersOut []*string                     `json:"teachersOut"`
	Number      *string                       `json:"number,omitempty"`
	Title       string                        `json:"title"`
	StartDate   *time.Time                    `json:"startDate,omitempty"`
	Duration    *string                       `json:"duration,omitempty"`
	Level       *string                       `json:"level,omitempty"`
	Rank        *string                       `json:"rank,omitempty"`
	Achievement *string                       `json:"achievement,omitempty"`
	Fund        *string                       `json:"fund,omitempty"`
	IsAward     bool                          `json:"isAward"`
	Awards      []*NewAwardScientificResearch `json:"awards"`
}

type NewTerm struct {
	Name    *string      `json:"name,omitempty"`
	Courses []*NewCourse `json:"courses"`
}

type NewUser struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type NewWorkday struct {
	Weekday int    `json:"weekday"`
	Section string `json:"section"`
}

type Paper struct {
	ID           string        `json:"id"`
	TeachersIn   []*UserExport `json:"teachersIn"`
	TeachersOut  []*string     `json:"teachersOut"`
	Title        *string       `json:"title,omitempty"`
	PublishDate  *time.Time    `json:"publishDate,omitempty"`
	Rank         *string       `json:"rank,omitempty"`
	JournalName  *string       `json:"journalName,omitempty"`
	JournalLevel *string       `json:"journalLevel,omitempty"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdateAt     time.Time     `json:"updateAt"`
}

type Password struct {
	ID          string    `json:"id"`
	URL         *string   `json:"url,omitempty"`
	AppName     *string   `json:"appName,omitempty"`
	Account     string    `json:"account"`
	Password    string    `json:"password"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}

type Query struct {
}

type ResetPassword struct {
	Email       *string `json:"email,omitempty"`
	Code        *string `json:"code,omitempty"`
	NewPassword *string `json:"newPassword,omitempty"`
}

type ScientificResearch struct {
	ID          string                     `json:"id"`
	TeachersIn  []*UserExport              `json:"teachersIn"`
	TeachersOut []*string                  `json:"teachersOut"`
	Number      *string                    `json:"number,omitempty"`
	Title       string                     `json:"title"`
	StartDate   *time.Time                 `json:"startDate,omitempty"`
	Duration    *string                    `json:"duration,omitempty"`
	Level       *string                    `json:"level,omitempty"`
	Rank        *string                    `json:"rank,omitempty"`
	Achievement *string                    `json:"achievement,omitempty"`
	Fund        *string                    `json:"fund,omitempty"`
	IsAward     bool                       `json:"isAward"`
	Awards      []*AwardScientificResearch `json:"awards"`
	CreatedAt   time.Time                  `json:"createdAt"`
	UpdateAt    time.Time                  `json:"updateAt"`
}

type Term struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Courses   []*Course `json:"courses"`
	CreatedAt time.Time `json:"createdAt"`
	UpdateAt  time.Time `json:"updateAt"`
}

type TermPreview struct {
	Name    *string          `json:"name,omitempty"`
	Courses []*CoursePreview `json:"courses,omitempty"`
}

type UpdateCourse struct {
	Teachers      []*string     `json:"teachers,omitempty"`
	Name          *string       `json:"name,omitempty"`
	Location      *string       `json:"location,omitempty"`
	Type          *string       `json:"type,omitempty"`
	Weeks         []*string     `json:"weeks,omitempty"`
	Schedule      []*NewWorkday `json:"schedule,omitempty"`
	StudentNumber *int          `json:"studentNumber,omitempty"`
	Background    *string       `json:"background,omitempty"`
}

type UpdateTerm struct {
	Name string `json:"name"`
}

type UpdateWorkday struct {
	Weekday *int    `json:"weekday,omitempty"`
	Section *string `json:"section,omitempty"`
}

type User struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Avatar      string    `json:"avatar"`
	PhoneNumber *string   `json:"phoneNumber,omitempty"`
	WechatToken *string   `json:"wechatToken,omitempty"`
	Activate    bool      `json:"activate"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdateAt    time.Time `json:"updateAt"`
}

type UserCreate struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserExport struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
}

type UserInfo struct {
	Username    *string `json:"username,omitempty"`
	Avatar      *string `json:"avatar,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

type Workday struct {
	Weekday int    `json:"weekday"`
	Section string `json:"section"`
}

type WorkdayPreview struct {
	Weekday *int    `json:"weekday,omitempty"`
	Section *string `json:"section,omitempty"`
}
